spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/shopdb?serverTimezone=UTC
    username: root
    password: 1234
  security:
    user:
      name: root
      password: a
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  tomcat:
    max-http-form-post-size: 1024MB
